# Generated by Django 6.0.2 on 2026-02-15 07:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('lock_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ga_company',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'db_table': 'ga_currency',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('payment_direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ga_payment_method',
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_prefix_start', models.CharField(max_length=16)),
                ('code_prefix_end', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.accountgroup')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_groups', to='accounting.company')),
            ],
            options={
                'db_table': 'ga_account_group',
                'unique_together': {('company', 'code_prefix_start', 'code_prefix_end')},
            },
        ),
        migrations.CreateModel(
            name='AccountRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_roots', to='accounting.company')),
            ],
            options={
                'db_table': 'ga_account_root',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=32)),
                ('reconcile', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountgroup')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountroot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.currency')),
            ],
            options={
                'db_table': 'ga_account',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_groups', to='accounting.company')),
            ],
            options={
                'db_table': 'ga_journal_group',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('journal_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('bank', 'Bank'), ('cash', 'Cash'), ('general', 'General')], default='general', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='accounting.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='accounting.currency')),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_journals', to='accounting.account')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='accounting.journalgroup')),
            ],
            options={
                'db_table': 'ga_journal',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('move_type', models.CharField(choices=[('entry', 'Journal Entry'), ('out_invoice', 'Customer Invoice'), ('in_invoice', 'Vendor Bill'), ('out_refund', 'Customer Credit Note'), ('in_refund', 'Vendor Credit Note')], default='entry', max_length=32)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='accounting.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='accounting.currency')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='accounting.journal')),
            ],
            options={
                'db_table': 'ga_move',
            },
        ),
        migrations.CreateModel(
            name='FullReconcile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='full_reconcile_exchanges', to='accounting.move')),
            ],
            options={
                'db_table': 'ga_full_reconcile',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_company', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='accounting.company')),
            ],
            options={
                'db_table': 'ga_partner',
            },
        ),
        migrations.AddField(
            model_name='move',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='accounting.partner'),
        ),
        migrations.CreateModel(
            name='PaymentMethodLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_lines', to='accounting.journal')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.paymentmethod')),
            ],
            options={
                'db_table': 'ga_payment_method_line',
                'unique_together': {('journal', 'payment_method')},
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_terms', to='accounting.company')),
            ],
            options={
                'db_table': 'ga_payment_term',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='move',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='accounting.paymentterm'),
        ),
        migrations.CreateModel(
            name='PaymentTermLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('value_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed'), ('balance', 'Balance')], max_length=16)),
                ('value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('due_type', models.CharField(choices=[('days_after_invoice_date', 'Days After Invoice Date'), ('days_after_end_of_month', 'Days After End Of Month')], default='days_after_invoice_date', max_length=32)),
                ('due_days', models.IntegerField(default=0)),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.paymentterm')),
            ],
            options={
                'db_table': 'ga_payment_term_line',
                'ordering': ('payment_term_id', 'sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_groups', to='accounting.company')),
            ],
            options={
                'db_table': 'ga_tax_group',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('amount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed'), ('division', 'Division')], default='percent', max_length=16)),
                ('amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('scope', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('none', 'None')], default='none', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='accounting.company')),
                ('tax_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='accounting.taxgroup')),
            ],
            options={
                'db_table': 'ga_tax',
            },
        ),
        migrations.CreateModel(
            name='TaxRepartitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('refund', 'Refund')], max_length=16)),
                ('repartition_type', models.CharField(choices=[('base', 'Base'), ('tax', 'Tax')], max_length=8)),
                ('factor_percent', models.DecimalField(decimal_places=6, default=Decimal('100'), max_digits=18)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_repartition_lines', to='accounting.account')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartition_lines', to='accounting.tax')),
            ],
            options={
                'db_table': 'ga_tax_repartition_line',
                'ordering': ('tax_id', 'document_type', 'sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MoveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('debit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('amount_currency', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_lines', to='accounting.account')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='move_lines', to='accounting.currency')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.move')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='move_lines', to='accounting.partner')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='move_lines', to='accounting.tax')),
                ('tax_repartition_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='move_lines', to='accounting.taxrepartitionline')),
            ],
            options={
                'db_table': 'ga_move_line',
            },
        ),
        migrations.CreateModel(
            name='PartialReconcile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('max_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partial_reconciles', to='accounting.company')),
                ('credit_move_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partial_credits', to='accounting.moveline')),
                ('debit_move_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partial_debits', to='accounting.moveline')),
                ('full_reconcile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partials', to='accounting.fullreconcile')),
            ],
            options={
                'db_table': 'ga_partial_reconcile',
                'indexes': [models.Index(fields=['company'], name='ga_partial__company_809f9a_idx'), models.Index(fields=['max_date'], name='ga_partial__max_dat_f9e2de_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('payment_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.currency')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.journal')),
                ('move', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='accounting.move')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.partner')),
                ('payment_method_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.paymentmethodline')),
            ],
            options={
                'db_table': 'ga_payment',
                'indexes': [models.Index(fields=['company', 'date'], name='ga_payment_company_2cd0aa_idx'), models.Index(fields=['state'], name='ga_payment_state_a8dad6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['company', 'date'], name='ga_move_company_dd593d_idx'),
        ),
        migrations.AddIndex(
            model_name='move',
            index=models.Index(fields=['state'], name='ga_move_state_136771_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxgroup',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='moveline',
            index=models.Index(fields=['account', 'date'], name='ga_move_lin_account_e226e7_idx'),
        ),
        migrations.AddIndex(
            model_name='moveline',
            index=models.Index(fields=['move'], name='ga_move_lin_move_id_d60b36_idx'),
        ),
    ]
