# Generated by Django 6.0.2 on 2026-02-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('phone_code', models.CharField(blank=True, max_length=8)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ga_country',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CountryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='accounting.country')),
            ],
            options={
                'db_table': 'ga_country_state',
                'ordering': ('country_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CountryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='accounting.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='accounting.countrystate')),
            ],
            options={
                'db_table': 'ga_country_city',
                'ordering': ('country_id', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='countrystate',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('country', 'code'), name='uniq_country_state_country_code_non_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='countrystate',
            unique_together={('country', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='countrycity',
            unique_together={('country', 'state', 'name')},
        ),
    ]
