# Generated by Django 6.0.2 on 2026-02-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_country_countrystate_countrycity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_currencies', to='accounting.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_currencies', to='accounting.currency')),
            ],
            options={
                'db_table': 'ga_country_currency',
                'ordering': ('country_id', '-is_default', 'currency_id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('country',), name='uniq_country_default_currency')],
                'unique_together': {('country', 'currency')},
            },
        ),
    ]
