# Generated by Django 6.0.2 on 2026-02-15 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_country_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('costing_method', models.CharField(choices=[('standard', 'Standard Price'), ('avco', 'Average Cost (AVCO)'), ('fifo', 'FIFO')], default='standard', max_length=16)),
                ('valuation_method', models.CharField(choices=[('manual_periodic', 'Manual Periodic'), ('automated', 'Automated')], default='manual_periodic', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='accounting.company')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_product_categories', to='accounting.account')),
                ('income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_product_categories', to='accounting.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.productcategory')),
                ('valuation_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valuation_product_categories', to='accounting.account')),
            ],
            options={
                'db_table': 'ga_product_category',
                'ordering': ('company_id', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='uniq_product_category_company_code_non_empty')],
                'unique_together': {('company', 'parent', 'name')},
            },
        ),
    ]
