# Generated by Django 6.0.2 on 2026-02-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_prefix_start', models.CharField(max_length=16)),
                ('code_prefix_end', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_group_templates', to='accounting.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.accountgrouptemplate')),
            ],
            options={
                'db_table': 'ga_account_group_template',
                'ordering': ('country_id', 'code_prefix_start', 'id'),
                'unique_together': {('country', 'code_prefix_start', 'code_prefix_end')},
            },
        ),
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=32)),
                ('reconcile', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_templates', to='accounting.country')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountgrouptemplate')),
            ],
            options={
                'db_table': 'ga_account_template',
                'ordering': ('country_id', 'code'),
                'unique_together': {('country', 'code')},
            },
        ),
    ]
