# Generated by Django 6.0.2 on 2026-02-15 11:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_accountgrouptemplate_accounttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('line_subtotal', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('line_tax', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='accounting.account')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='accounting.move')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='accounting.tax')),
            ],
            options={
                'db_table': 'ga_invoice_line',
                'ordering': ('move_id', 'id'),
                'indexes': [models.Index(fields=['move'], name='ga_invoice__move_id_72a975_idx'), models.Index(fields=['account'], name='ga_invoice__account_82d686_idx')],
            },
        ),
    ]
