# Generated by Django 6.0.2 on 2026-02-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_invoiceline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_return_periodicity', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=16)),
                ('tax_return_reminder_days', models.PositiveSmallIntegerField(default=7)),
                ('tax_rounding_method', models.CharField(choices=[('round_per_line', 'Round per Line'), ('round_globally', 'Round Globally')], default='round_per_line', max_length=24)),
                ('account_price_include', models.CharField(choices=[('tax_included', 'Tax Included'), ('tax_excluded', 'Tax Excluded')], default='tax_excluded', max_length=16)),
                ('tax_exigibility', models.BooleanField(default=False)),
                ('fiscalyear_last_day', models.PositiveSmallIntegerField(default=31)),
                ('fiscalyear_last_month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='12', max_length=2)),
                ('use_anglo_saxon', models.BooleanField(default=False)),
                ('invoicing_switch_threshold', models.DateField(blank=True, null=True)),
                ('predict_bill_product', models.BooleanField(default=False)),
                ('followup_enabled', models.BooleanField(default=True)),
                ('multi_ledger_enabled', models.BooleanField(default=False)),
                ('budgets_enabled', models.BooleanField(default=False)),
                ('assets_enabled', models.BooleanField(default=False)),
                ('online_payments_enabled', models.BooleanField(default=False)),
                ('quick_edit_mode', models.CharField(choices=[('none', 'Disabled'), ('warning', 'Warning'), ('allow', 'Allow')], default='none', max_length=16)),
                ('check_account_audit_trail', models.BooleanField(default=False)),
                ('autopost_bills', models.BooleanField(default=False)),
                ('account_use_credit_limit', models.BooleanField(default=False)),
                ('account_default_credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account_storno', models.BooleanField(default=False)),
                ('qr_code', models.BooleanField(default=False)),
                ('invoice_terms', models.TextField(blank=True)),
                ('use_invoice_terms', models.BooleanField(default=False)),
                ('generate_deferred_expense_entries_method', models.CharField(choices=[('manual', 'Manual'), ('on_posting', 'On Posting')], default='manual', max_length=16)),
                ('deferred_expense_amount_computation_method', models.CharField(choices=[('day_count', 'Day Count'), ('equal_per_period', 'Equal per Period')], default='day_count', max_length=24)),
                ('generate_deferred_revenue_entries_method', models.CharField(choices=[('manual', 'Manual'), ('on_posting', 'On Posting')], default='manual', max_length=16)),
                ('deferred_revenue_amount_computation_method', models.CharField(choices=[('day_count', 'Day Count'), ('equal_per_period', 'Equal per Period')], default='day_count', max_length=24)),
                ('account_cash_basis_base_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_basis_base_settings', to='accounting.account')),
                ('bank_suspense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_suspense_settings', to='accounting.account')),
                ('chart_template_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_settings_chart_template', to='accounting.country')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_settings', to='accounting.company')),
                ('currency_exchange_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_exchange_settings', to='accounting.journal')),
                ('default_purchase_payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_purchase_settings', to='accounting.paymentterm')),
                ('default_purchase_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_purchase_settings', to='accounting.tax')),
                ('default_sale_payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_sale_settings', to='accounting.paymentterm')),
                ('default_sales_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_sales_settings', to='accounting.tax')),
                ('deferred_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deferred_expense_account_settings', to='accounting.account')),
                ('deferred_expense_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deferred_expense_journal_settings', to='accounting.journal')),
                ('deferred_revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deferred_revenue_account_settings', to='accounting.account')),
                ('deferred_revenue_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deferred_revenue_journal_settings', to='accounting.journal')),
                ('expense_currency_exchange_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_currency_exchange_settings', to='accounting.account')),
                ('fiscal_localization_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_settings_localization', to='accounting.country')),
                ('income_currency_exchange_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_currency_exchange_settings', to='accounting.account')),
                ('tax_cash_basis_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_cash_basis_settings', to='accounting.journal')),
                ('tax_return_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_return_settings', to='accounting.journal')),
                ('transfer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_settings', to='accounting.account')),
            ],
            options={
                'db_table': 'ga_accounting_settings',
            },
        ),
    ]
