# Generated by Django 6.0.2 on 2026-02-17 15:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_invoiceline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=64, null=True)),
                ("acquisition_date", models.DateField()),
                ("first_depreciation_date", models.DateField(blank=True, null=True)),
                ("original_value", models.DecimalField(decimal_places=6, max_digits=18)),
                ("salvage_value", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=18)),
                ("method", models.CharField(choices=[("linear", "Linear"), ("degressive", "Degressive")], default="linear", max_length=16)),
                ("method_number", models.PositiveIntegerField(default=5)),
                ("method_period", models.PositiveIntegerField(default=12)),
                ("prorata", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("asset_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="accounting.account")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="accounting.company")),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="accounting.currency",
                    ),
                ),
                (
                    "depreciation_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets_depreciation",
                        to="accounting.account",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets_expense",
                        to="accounting.account",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="accounting.journal",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="accounting.partner",
                    ),
                ),
            ],
            options={
                "db_table": "ga_asset",
                "unique_together": {("company", "code")},
                "indexes": [
                    models.Index(fields=["company", "acquisition_date"], name="ga_asset_company_bbf708_idx"),
                    models.Index(fields=["state"], name="ga_asset_state_4f0a6c_idx"),
                    models.Index(fields=["active"], name="ga_asset_active_63fdc0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetDepreciationLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=6, max_digits=18)),
                ("depreciated_value", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=18)),
                ("residual_value", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=18)),
                ("state", models.CharField(choices=[("draft", "Draft"), ("posted", "Posted")], default="draft", max_length=16)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="depreciation_lines", to="accounting.asset")),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_depreciation_lines",
                        to="accounting.move",
                    ),
                ),
            ],
            options={
                "db_table": "ga_asset_depreciation_line",
                "ordering": ("asset_id", "sequence", "id"),
                "unique_together": {("asset", "sequence")},
                "indexes": [
                    models.Index(fields=["asset", "date"], name="ga_asset_de_asset_i_077152_idx"),
                    models.Index(fields=["state"], name="ga_asset_de_state_0d2332_idx"),
                ],
            },
        ),
    ]
