# Generated by Django 6.0.2 on 2026-02-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_accountingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='accounting.company')),
            ],
            options={
                'db_table': 'ga_financial_budget',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FinancialBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('planned_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('practical_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.financialbudget')),
            ],
            options={
                'db_table': 'ga_financial_budget_line',
            },
        ),
        migrations.CreateModel(
            name='FiscalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('auto_apply', models.BooleanField(default=False)),
                ('vat_required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_positions', to='accounting.company')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_positions', to='accounting.country')),
            ],
            options={
                'db_table': 'ga_fiscal_position',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('disabled', 'Disabled'), ('test', 'Test'), ('enabled', 'Enabled')], default='disabled', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_providers', to='accounting.company')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_providers', to='accounting.journal')),
            ],
            options={
                'db_table': 'ga_payment_provider',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ReconciliationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('auto_reconcile', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_models', to='accounting.company')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_models', to='accounting.journal')),
            ],
            options={
                'db_table': 'ga_reconciliation_model',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReconciliationModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('label', models.CharField(max_length=255)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], default='fixed', max_length=16)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_model_lines', to='accounting.account')),
                ('reconciliation_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.reconciliationmodel')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_model_lines', to='accounting.tax')),
            ],
            options={
                'db_table': 'ga_reconciliation_model_line',
                'ordering': ('reconciliation_model_id', 'sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('linear', 'Linear'), ('degressive', 'Degressive')], default='linear', max_length=16)),
                ('method_number', models.PositiveIntegerField(default=5)),
                ('method_period_months', models.PositiveIntegerField(default=12)),
                ('prorata', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('account_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_model_asset_accounts', to='accounting.account')),
                ('account_depreciation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_model_depr_accounts', to='accounting.account')),
                ('account_expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_model_expense_accounts', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_models', to='accounting.company')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_models', to='accounting.journal')),
            ],
            options={
                'db_table': 'ga_asset_model',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder', models.CharField(blank=True, max_length=255)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('swift', models.CharField(blank=True, max_length=32)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.company')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.journal')),
            ],
            options={
                'db_table': 'ga_bank_account',
                'unique_together': {('company', 'journal')},
            },
        ),
        migrations.CreateModel(
            name='DisallowedExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('disallow_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disallowed_expense_categories', to='accounting.company')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disallowed_expense_categories', to='accounting.account')),
            ],
            options={
                'db_table': 'ga_disallowed_expense_category',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FiscalPositionAccountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_dest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_position_account_dest', to='accounting.account')),
                ('account_src', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_position_account_src', to='accounting.account')),
                ('fiscal_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_maps', to='accounting.fiscalposition')),
            ],
            options={
                'db_table': 'ga_fiscal_position_account_map',
                'unique_together': {('fiscal_position', 'account_src')},
            },
        ),
        migrations.CreateModel(
            name='FiscalPositionTaxMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_maps', to='accounting.fiscalposition')),
                ('tax_dest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_position_tax_dest', to='accounting.tax')),
                ('tax_src', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_position_tax_src', to='accounting.tax')),
            ],
            options={
                'db_table': 'ga_fiscal_position_tax_map',
                'unique_together': {('fiscal_position', 'tax_src')},
            },
        ),
        migrations.CreateModel(
            name='FollowupLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('delay_days', models.IntegerField(default=0)),
                ('action', models.CharField(choices=[('email', 'Send Email'), ('call', 'Call'), ('manual', 'Manual Action')], default='email', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followup_levels', to='accounting.company')),
            ],
            options={
                'db_table': 'ga_followup_level',
                'ordering': ('company_id', 'delay_days', 'id'),
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounting.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounting.currency')),
            ],
            options={
                'db_table': 'ga_ledger',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='uniq_company_default_ledger')],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_methods', to='accounting.paymentmethod')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_methods', to='accounting.paymentprovider')),
            ],
            options={
                'db_table': 'ga_payment_provider_method',
                'unique_together': {('provider', 'payment_method')},
            },
        ),
    ]
