# Generated by Django 6.0.2 on 2026-02-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_financialbudget_financialbudgetline_fiscalposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='account_discount_expense_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_expense_allocation_settings', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='account_discount_income_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_income_allocation_settings', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='account_fiscal_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_settings_fiscal_country', to='accounting.country'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='account_journal_early_pay_discount_gain_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='early_discount_gain_settings', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='account_journal_early_pay_discount_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='early_discount_loss_settings', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='account_journal_suspense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_suspense_settings', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='chart_template',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_settings', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='display_invoice_amount_total_words',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='display_invoice_tax_company_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='group_analytic_accounting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='group_cash_rounding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='group_multi_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='group_sale_delivery_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='group_show_purchase_receipts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='group_show_sale_receipts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='group_uom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='group_warning_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='has_accounting_entries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='has_chart_of_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='incoterm',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='is_account_peppol_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_bank_statement_import_camt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_bank_statement_import_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_bank_statement_import_ofx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_bank_statement_import_qif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_batch_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_check_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_extract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_intrastat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_iso20022',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_peppol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_account_sepa_direct_debit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_currency_rate_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_l10n_eu_oss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_product_margin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='module_snailmail_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='preview_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='terms_type',
            field=models.CharField(choices=[('html', 'HTML'), ('plain', 'Plain Text')], default='html', max_length=16),
        ),
    ]
