# Generated by Django 6.0.2 on 2026-02-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_asset_assetdepreciationline'),
        ('accounting', '0010_accountingsettings_account_discount_expense_allocation_and_more'),
    ]

    operations = [
    ]
