# Generated by Django 6.0.2 on 2026-02-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_merge_20260218_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ga_analytic_account',
            },
        ),
        migrations.CreateModel(
            name='AnalyticDistributionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('account_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ga_analytic_distribution_model',
            },
        ),
        migrations.CreateModel(
            name='AnalyticDistributionModelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
            options={
                'db_table': 'ga_analytic_distribution_model_line',
                'ordering': ('model_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnalyticPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('default_applicability', models.CharField(choices=[('optional', 'Optional'), ('mandatory', 'Mandatory'), ('unavailable', 'Unavailable')], default='optional', max_length=16)),
                ('color', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ga_analytic_plan',
            },
        ),
        migrations.AddField(
            model_name='analyticaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytic_accounts', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='analyticaccount',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytic_accounts', to='accounting.partner'),
        ),
        migrations.AddField(
            model_name='analyticdistributionmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytic_distribution_models', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='analyticdistributionmodel',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytic_distribution_models', to='accounting.partner'),
        ),
        migrations.AddField(
            model_name='analyticdistributionmodel',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytic_distribution_models', to='accounting.productcategory'),
        ),
        migrations.AddField(
            model_name='analyticdistributionmodelline',
            name='analytic_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lines', to='accounting.analyticaccount'),
        ),
        migrations.AddField(
            model_name='analyticdistributionmodelline',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.analyticdistributionmodel'),
        ),
        migrations.AddField(
            model_name='analyticplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytic_plans', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='analyticplan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.analyticplan'),
        ),
        migrations.AddField(
            model_name='analyticaccount',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.analyticplan'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticdistributionmodel',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='analyticdistributionmodelline',
            unique_together={('model', 'analytic_account')},
        ),
        migrations.AlterUniqueTogether(
            name='analyticplan',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='analyticaccount',
            unique_together={('company', 'name')},
        ),
    ]
