# Generated by Django 6.0.2 on 2026-02-18 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_analyticaccount_analyticdistributionmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='accounting.country'),
        ),
        migrations.AddField(
            model_name='partner',
            name='customer_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='mobile',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partner',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.partner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='accounting.countrystate'),
        ),
        migrations.AddField(
            model_name='partner',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='street2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='supplier_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('contact', 'Contact'), ('invoice', 'Invoice Address'), ('delivery', 'Delivery Address'), ('other', 'Other Address')], default='contact', max_length=16),
        ),
        migrations.AddField(
            model_name='partner',
            name='vat',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partner',
            name='zip',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['company', 'name'], name='ga_partner_company_05817c_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['company', 'customer_rank'], name='ga_partner_company_b24c34_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['active'], name='ga_partner_active_2e5e41_idx'),
        ),
    ]
