# Generated by Django 6.0.2 on 2026-02-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_rename_ga_asset_company_bbf708_idx_ga_asset_company_3e9566_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('default_code', models.CharField(blank=True, default='', max_length=64)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('product_type', models.CharField(choices=[('consu', 'Consumable'), ('service', 'Service'), ('product', 'Storable Product')], default='consu', max_length=16)),
                ('sale_ok', models.BooleanField(default=True)),
                ('purchase_ok', models.BooleanField(default=True)),
                ('list_price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('standard_price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ga_product',
                'ordering': ('company_id', 'name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounting.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_products', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_products', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_products', to='accounting.tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_products', to='accounting.tax'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('default_code', ''), _negated=True), fields=('company', 'default_code'), name='uniq_product_company_default_code_non_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'name')},
        ),
    ]
