# Generated by Django 6.0.2 on 2026-02-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_product_and_more'),
    ]

    operations = []
