# Generated by Django 6.0.2 on 2026-02-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_move_reversed_entry'),
    ]

    operations = []
