# Generated by Django 6.0.2 on 2026-02-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_rename_ga_asset_company_bbf708_idx_ga_asset_company_3e9566_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='debit_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_entries', to='accounting.move'),
        ),
        migrations.AddField(
            model_name='move',
            name='is_debit_note',
            field=models.BooleanField(default=False),
        ),
    ]
