# Generated by Django 6.0.2 on 2026-02-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_partner_supplier_rank_and_customer_rank'),
        ('accounting', '0018_move_debit_origin_move_is_debit_note'),
    ]

    operations = [
    ]
