# Generated by Django 6.0.2 on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0019_merge_20260218_1422"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("date_start", models.DateField()),
                ("date_stop", models.DateField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("month", "Monthly"), ("quarter", "Quarterly"), ("year", "Yearly")],
                        default="month",
                        max_length=16,
                    ),
                ),
                ("move_ids_count", models.PositiveIntegerField(default=0)),
                ("total_percent", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                (
                    "state",
                    models.CharField(
                        choices=[("disabled", "Disabled"), ("in_progress", "Running")],
                        default="disabled",
                        max_length=16,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_models",
                        to="accounting.company",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_models",
                        to="accounting.journal",
                    ),
                ),
                (
                    "accounts",
                    models.ManyToManyField(blank=True, related_name="source_transfer_models", to="accounting.account"),
                ),
            ],
            options={
                "db_table": "ga_transfer_model",
                "indexes": [
                    models.Index(fields=["company", "state"], name="ga_transfer_company_407038_idx"),
                    models.Index(fields=["journal", "date_start"], name="ga_transfer_journal_e458b9_idx"),
                ],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="TransferModelLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("percent", models.DecimalField(decimal_places=6, default=100, max_digits=9)),
                ("percent_is_readonly", models.BooleanField(default=False)),
                ("sequence", models.IntegerField(default=10)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_transfer_lines",
                        to="accounting.account",
                    ),
                ),
                (
                    "transfer_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.transfermodel",
                    ),
                ),
                (
                    "analytic_accounts",
                    models.ManyToManyField(blank=True, related_name="transfer_model_lines", to="accounting.analyticaccount"),
                ),
                (
                    "partners",
                    models.ManyToManyField(blank=True, related_name="transfer_model_lines", to="accounting.partner"),
                ),
            ],
            options={
                "db_table": "ga_transfer_model_line",
                "ordering": ("sequence", "id"),
                "unique_together": {("transfer_model", "account")},
            },
        ),
        migrations.AddField(
            model_name="move",
            name="transfer_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moves",
                to="accounting.transfermodel",
            ),
        ),
        migrations.AddField(
            model_name="moveline",
            name="analytic_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="move_lines",
                to="accounting.analyticaccount",
            ),
        ),
    ]
