# Generated by Django 6.0.2 on 2026-02-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_company_city_company_company_details_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_groups', to='accounting.country'),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='sequence',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='tax_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_groups_payable', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='tax_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_groups_receivable', to='accounting.account'),
        ),
    ]
