# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0020_transfermodel_transfermodelline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moveline",
            name="analytic_distribution",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
