# Generated by Django 6.0.2 on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0021_moveline_analytic_distribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("amount", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("unit_amount", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("uom_name", models.CharField(blank=True, default="", max_length=64)),
                ("ref", models.CharField(blank=True, default="", max_length=255)),
                ("analytic_distribution", models.JSONField(blank=True, default=dict)),
                ("project", models.CharField(blank=True, default="", max_length=255)),
                ("task", models.CharField(blank=True, default="", max_length=255)),
                (
                    "analytic_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analytic_lines",
                        to="accounting.analyticaccount",
                    ),
                ),
                (
                    "auto_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auto_analytic_lines",
                        to="accounting.analyticaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analytic_lines",
                        to="accounting.company",
                    ),
                ),
                (
                    "general_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analytic_lines",
                        to="accounting.account",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analytic_lines",
                        to="accounting.journal",
                    ),
                ),
                (
                    "move_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analytic_lines",
                        to="accounting.moveline",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analytic_lines",
                        to="accounting.partner",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analytic_lines",
                        to="accounting.product",
                    ),
                ),
            ],
            options={
                "db_table": "ga_analytic_line",
                "indexes": [
                    models.Index(fields=["company", "date"], name="ga_analytic_company_a10af2_idx"),
                    models.Index(fields=["analytic_account"], name="ga_analytic_analyti_fb96a5_idx"),
                    models.Index(fields=["move_line"], name="ga_analytic_move_li_566394_idx"),
                ],
            },
        ),
    ]
