# Generated by Django 6.0.2 on 2026-02-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_taxgroup_active_taxgroup_country_and_more'),
        ('accounting', '0022_analyticline'),
    ]

    operations = [
    ]
