# Generated by Django 6.0.2 on 2026-02-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_merge_20260222_1255'),
        ('accounting', '0023_merge_20260222_1459'),
    ]

    operations = [
    ]
