# Generated by Django 6.0.2 on 2026-02-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_merge_20260223_0834'),
        ('accounting', '0024_usercompanyaccess'),
    ]

    operations = [
    ]
